name: Validate ownerships

on:
  push:

jobs:
  validate-ownership:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: "Install codeowner enforcer"
        run: |
          npm install --global codeowners
          npm install --global codeowners-enforcer

      - name: "List all files with owner"
        run: output=$(codeowners audit --unowned | while read -r line; do if [[ ! -d $line ]]; then echo "$line"; fi; done) && [[ -n "$output" ]] && echo "$output" && exit 1

      - name: "Verify all files is owned"
        run: codeowners-enforcer



